### ISSUE TITLE
AGPL or MIT license?

### ISSUE THREAD

**Issue by bradh** [8kdata/adsb-sbs1#6]
The top level LICENSE file says AGPL, but the individual code files have headers that basically look like an MIT license. Can you say which is intended?

**Comment by ahachete** [comment]
TBH code is not finished nor maintained, but if it would be useful I'm happy to relicense to any convenient license. Apache2?

**Comment by bradh** [comment]
I'm not sure that I'll go with this approach, but I'm certainly OK with Apache 2.
